---
title: "Read in Microbiome Data"
author: "MD"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
 html_document:
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---



```{r}
library(xlsx)
library(phyloseq)

source('Functions/Microbiome_Functions.R')
```

```{r}
d.a <- read.delim('Data/Inputs/demultiplex_plateA.log',sep=',',header=TRUE)
write.xlsx(d.a, 'Data/Outputs/Intermediate_Data/demultiplex_plateA.xlsx')

d.b <- read.delim('Data/Inputs/demultiplex_plateA.log',sep=',',header=TRUE)
write.xlsx(d.b, 'Data/Outputs/Intermediate_Data/demultiplex_plateB.xlsx')

d.c <- read.delim('Data/Inputs/demultiplex_plateA.log',sep=',',header=TRUE)
write.xlsx(d.c, 'Data/Outputs/Intermediate_Data/demultiplex_plateC.xlsx')
```


```{r}
P.A <- emu_to_phyloseq(RA_file = 'Data/Inputs/EMU_Relative_Abundance_plateA.csv',
                        meta_file = 'Data/Inputs/demultiplex_plateA.xlsx',
                        sheet = 'A_demultiplex',range = 'A1:L81',
                        sample_names = 'Name',
                        run_name = 'Mary.A')
saveRDS(P.A,'Data/Outputs/Intermediate_Data/Phyloseq.Plate.A.RDS')

P.B <- emu_to_phyloseq(RA_file = 'Data/Inputs/EMU_Relative_Abundance_plateB.csv',
                        meta_file = 'Data/Inputs/demultiplex_plateB.xlsx',
                        sheet = 'B_demultiplex',range = 'A1:L81',
                        sample_names = 'Name',
                        run_name = 'Mary.B')
saveRDS(P.B,'Data/Outputs/Intermediate_Data/Phyloseq.Plate.B.RDS')


P.C <- emu_to_phyloseq(RA_file = 'Data/Inputs/EMU_Relative_Abundance_plateC.csv',
                        meta_file = 'Data/Inputs/demultiplex_plateC.xlsx',
                        sheet = 'C_demultiplex',range = 'A1:L81',
                        sample_names = 'Name',
                        run_name = 'Mary.C')
saveRDS(P.C,'Data/Outputs/Intermediate_Data/Phyloseq.Plate.C.RDS')

P.rel <- merge_phyloseq(P.A,P.B,P.C)
saveRDS(P.rel, 'Data/Outputs/Intermediate_Data/Phyloseq.RelativeAbundance.RDS')

P.count <- P.rel
for (n in 1:nsamples(P.count)) {
  otu_table(P.count)[,n] <- round(otu_table(P.count)[,n] * sample_data(P.count)$final[n], 0)
}
saveRDS(P.count, 'Data/Outputs/Intermediate_Data/Phyloseq.Count.Data.RDS')

```



